-- Delete
delete from TENJIN_TEMPLATESTRUCTURE where TEMPLATESTRUCTURE_ID >= 1394;
delete from TENJIN_TEMPLATEELEMENT_I18N where TEMPLATEELEMENT_ID >= 48;
delete from TENJIN_TEMPLATEELEMENT where TEMPLATEELEMENT_ID >= 48;
delete from TENJIN_TEMPLATE where TEMPLATE_ID = 3;
-- Template
insert into TENJIN_TEMPLATE (TEMPLATE_ID, TITLE, DESCRIPTION, ACTIVE) values (3, 'Plan de cours simplifié (doctorat)', 'Plan de cours simplifié (doctorat)', 1);

-- Présentation du cours
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (48, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introduction et présentation du site', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introduction and presentation of the site', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introducción y presentación del sitio', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1394, 1, 1, NULL, 48, NULL, 3, 0);

-- Présentation du cours -> Description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1395, 1, 0, 1394, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1396, 0, 0, 1395, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1397, 0, 0, 1395, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1398, 0, 0, 1395, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1399, 0, 0, 1395, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1400, 0, 0, 1395, 17, NULL, NULL, 4);

-- Présentation du cours -> Objectifs
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1401, 0, 0, 1394, 19, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1402, 0, 0, 1401, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1403, 0, 0, 1401, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1404, 0, 0, 1401, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1405, 0, 0, 1401, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1406, 0, 0, 1401, 17, NULL, NULL, 4);

-- Présentation du cours -> approche
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1407, 0, 0, 1394, 20, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1408, 0, 0, 1407, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1409, 0, 0, 1407, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1410, 0, 0, 1407, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1411, 0, 0, 1407, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1412, 0, 0, 1407, 17, NULL, NULL, 4);

-- Coordinates
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (49, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Coordonnées des personnes ressources', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Contact information', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Información de contacto', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1413, 1, 1, NULL, 49, NULL, 3, 1);

-- Coordinates -> coordinator
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1414, 0, 0, 1413, 21, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1415, 0, 0, 1414, 6, NULL, NULL, 0);

-- Coordinates -> teacher
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1416, 0, 0, 1413, 22, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1417, 0, 0, 1416, 6, NULL, NULL, 0);

-- Coordinates -> assistant
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1418, 0, 0, 1413, 23, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1419, 0, 0, 1418, 6, NULL, NULL, 0);

-- Coordinates -> speaker
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1420, 0, 0, 1413, 24, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1421, 0, 0, 1420, 6, NULL, NULL, 0);

-- Coordinates -> secretary
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1422, 0, 0, 1413, 25, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1423, 0, 0, 1422, 6, NULL, NULL, 0);

-- Organisation du cours
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (50, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Contenu et informations pertinentes', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Content and relevant information', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Contenido e información relevante', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1424, 1, 1, NULL, 50, NULL, 3, 2);

-- Oganisation du cours -> regroupement
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1425, 0, 1, 1424, 14, NULL, NULL, 0);

-- Oganisation du cours -> regroupement -> séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1426, 0, 1, 1425, 12, NULL, NULL, 0);

-- Oganisation du cours -> regroupement -> séance -> description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1427, 0, 0, 1426, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1428, 0, 0, 1427, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1429, 0, 0, 1427, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1430, 0, 0, 1427, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1431, 0, 0, 1427, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1432, 0, 0, 1427, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1433, 0, 0, 1427, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1434, 0, 0, 1427, 8, NULL, NULL, 6);

-- Generated Wed Apr 03 2019 16:28:43 GMT-0400 (GMT-04:00)
