-- Delete
delete from TENJIN_TEMPLATESTRUCTURE where TEMPLATESTRUCTURE_ID >= 1394;
delete from TENJIN_TEMPLATEELEMENT_I18N where TEMPLATEELEMENT_ID >= 48;
delete from TENJIN_TEMPLATEELEMENT where TEMPLATEELEMENT_ID >= 48;
delete from TENJIN_TEMPLATE where TEMPLATE_ID = 3;
