-- Template
insert into TENJIN_TEMPLATE (TEMPLATE_ID, TITLE, DESCRIPTION, ACTIVE) values (3, 'Plan de cours simplifié (doctorat)', 'Plan de cours simplifié (doctorat)', 1);

-- Présentation du cours
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (48, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introduction et présentation du site', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introduction and presentation of the site', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (48, 'Introducción y presentación del sitio', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1394, 1, 1, NULL, 48, NULL, 3, 0);

-- Présentation du cours -> Description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1395, 1, 0, 1394, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1396, 0, 0, 1395, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1397, 0, 0, 1395, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1398, 0, 0, 1395, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1399, 0, 0, 1395, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1400, 0, 0, 1395, 17, NULL, NULL, 4);

-- Présentation du cours -> Objectifs
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1401, 0, 0, 1394, 19, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1402, 0, 0, 1401, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1403, 0, 0, 1401, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1404, 0, 0, 1401, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1405, 0, 0, 1401, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1406, 0, 0, 1401, 17, NULL, NULL, 4);

-- Présentation du cours -> approche
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1407, 0, 0, 1394, 20, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1408, 0, 0, 1407, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1409, 0, 0, 1407, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1410, 0, 0, 1407, 4, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1411, 0, 0, 1407, 16, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1412, 0, 0, 1407, 17, NULL, NULL, 4);

-- Coordinates
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (49, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Coordonnées des personnes ressources', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Contact information', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (49, 'Información de contacto', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1413, 1, 1, NULL, 49, NULL, 3, 1);

-- Coordinates -> coordinator
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1414, 0, 0, 1413, 21, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1415, 0, 0, 1414, 6, NULL, NULL, 0);

-- Coordinates -> teacher
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1416, 0, 0, 1413, 22, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1417, 0, 0, 1416, 6, NULL, NULL, 0);

-- Coordinates -> assistant
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1418, 0, 0, 1413, 23, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1419, 0, 0, 1418, 6, NULL, NULL, 0);

-- Coordinates -> speaker
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1420, 0, 0, 1413, 24, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1421, 0, 0, 1420, 6, NULL, NULL, 0);

-- Coordinates -> secretary
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1422, 0, 0, 1413, 25, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1423, 0, 0, 1422, 6, NULL, NULL, 0);

-- Organisation du cours
insert into TENJIN_TEMPLATEELEMENT (TEMPLATEELEMENT_ID, TEMPLATEELEMENTTYPE_ID) values (50, 1);
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Contenu et informations pertinentes', 'fr_CA');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Content and relevant information', 'en_US');
insert into TENJIN_TEMPLATEELEMENT_I18N (TEMPLATEELEMENT_ID, LABEL, LOCALE) values (50, 'Contenido e información relevante', 'es_ES');
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1424, 1, 1, NULL, 50, NULL, 3, 2);

-- Oganisation du cours -> regroupement
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1425, 0, 1, 1424, 14, NULL, NULL, 0);

-- Oganisation du cours -> regroupement -> séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1426, 0, 1, 1425, 12, NULL, NULL, 0);

-- Séance -> description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1427, 0, 0, 1426, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1428, 0, 0, 1427, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1429, 0, 0, 1427, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1430, 0, 0, 1427, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1431, 0, 0, 1427, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1432, 0, 0, 1427, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1433, 0, 0, 1427, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1434, 0, 0, 1427, 8, NULL, NULL, 6);

-- Séance -> objectives
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1435, 0, 0, 1426, 19, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1436, 0, 0, 1435, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1437, 0, 0, 1435, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1438, 0, 0, 1435, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1439, 0, 0, 1435, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1440, 0, 0, 1435, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1441, 0, 0, 1435, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1442, 0, 0, 1435, 8, NULL, NULL, 6);

-- Séance -> avant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1443, 0, 0, 1426, 35, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1444, 0, 0, 1443, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1445, 0, 0, 1443, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1446, 0, 0, 1443, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1447, 0, 0, 1443, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1448, 0, 0, 1443, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1449, 0, 0, 1443, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1450, 0, 0, 1443, 8, NULL, NULL, 6);

-- Séance -> durant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1451, 0, 0, 1426, 36, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1452, 0, 0, 1451, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1453, 0, 0, 1451, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1454, 0, 0, 1451, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1455, 0, 0, 1451, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1456, 0, 0, 1451, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1457, 0, 0, 1451, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1458, 0, 0, 1451, 8, NULL, NULL, 6);

-- Séance -> après la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1459, 0, 0, 1426, 37, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1460, 0, 0, 1459, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1461, 0, 0, 1459, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1462, 0, 0, 1459, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1463, 0, 0, 1459, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1464, 0, 0, 1459, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1465, 0, 0, 1459, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1466, 0, 0, 1459, 8, NULL, NULL, 6);

-- Oganisation du cours -> séance de cours
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1467, 0, 1, 1424, 12, NULL, NULL, 1);

-- Séance -> description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1468, 0, 0, 1467, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1469, 0, 0, 1468, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1470, 0, 0, 1468, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1471, 0, 0, 1468, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1472, 0, 0, 1468, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1473, 0, 0, 1468, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1474, 0, 0, 1468, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1475, 0, 0, 1468, 8, NULL, NULL, 6);

-- Séance -> objectives
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1476, 0, 0, 1467, 19, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1477, 0, 0, 1476, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1478, 0, 0, 1476, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1479, 0, 0, 1476, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1480, 0, 0, 1476, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1481, 0, 0, 1476, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1482, 0, 0, 1476, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1483, 0, 0, 1476, 8, NULL, NULL, 6);

-- Séance -> avant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1484, 0, 0, 1467, 35, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1485, 0, 0, 1484, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1486, 0, 0, 1484, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1487, 0, 0, 1484, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1488, 0, 0, 1484, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1489, 0, 0, 1484, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1490, 0, 0, 1484, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1491, 0, 0, 1484, 8, NULL, NULL, 6);

-- Séance -> durant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1492, 0, 0, 1467, 36, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1493, 0, 0, 1492, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1494, 0, 0, 1492, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1495, 0, 0, 1492, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1496, 0, 0, 1492, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1497, 0, 0, 1492, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1498, 0, 0, 1492, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1499, 0, 0, 1492, 8, NULL, NULL, 6);

-- Séance -> après la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1500, 0, 0, 1467, 37, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1501, 0, 0, 1500, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1502, 0, 0, 1500, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1503, 0, 0, 1500, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1504, 0, 0, 1500, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1505, 0, 0, 1500, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1506, 0, 0, 1500, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1507, 0, 0, 1500, 8, NULL, NULL, 6);

-- Oganisation du cours -> séance de traveaux pratiques
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1508, 0, 1, 1424, 13, NULL, NULL, 2);

-- Séance -> description
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1509, 0, 0, 1508, 18, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1510, 0, 0, 1509, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1511, 0, 0, 1509, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1512, 0, 0, 1509, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1513, 0, 0, 1509, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1514, 0, 0, 1509, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1515, 0, 0, 1509, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1516, 0, 0, 1509, 8, NULL, NULL, 6);

-- Séance -> objectives
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1517, 0, 0, 1508, 19, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1518, 0, 0, 1517, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1519, 0, 0, 1517, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1520, 0, 0, 1517, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1521, 0, 0, 1517, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1522, 0, 0, 1517, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1523, 0, 0, 1517, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1524, 0, 0, 1517, 8, NULL, NULL, 6);

-- Séance -> avant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1525, 0, 0, 1508, 35, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1526, 0, 0, 1525, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1527, 0, 0, 1525, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1528, 0, 0, 1525, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1529, 0, 0, 1525, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1530, 0, 0, 1525, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1531, 0, 0, 1525, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1532, 0, 0, 1525, 8, NULL, NULL, 6);

-- Séance -> durant la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1533, 0, 0, 1508, 36, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1534, 0, 0, 1533, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1535, 0, 0, 1533, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1536, 0, 0, 1533, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1537, 0, 0, 1533, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1538, 0, 0, 1533, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1539, 0, 0, 1533, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1540, 0, 0, 1533, 8, NULL, NULL, 6);

-- Séance -> après la séance
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1541, 0, 0, 1508, 37, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1542, 0, 0, 1541, 2, NULL, NULL, 0);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1543, 0, 0, 1541, 3, NULL, NULL, 1);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1544, 0, 0, 1541, 16, NULL, NULL, 2);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1545, 0, 0, 1541, 17, NULL, NULL, 3);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1546, 0, 0, 1541, 4, NULL, NULL, 4);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1547, 0, 0, 1541, 15, NULL, NULL, 5);
insert into TENJIN_TEMPLATESTRUCTURE (TEMPLATESTRUCTURE_ID, MANDATORY, DISPLAY_IN_MENU, PARENT_ID, TEMPLATEELEMENT_ID, PROVIDER_ID, TEMPLATE_ID, DISPLAY_ORDER) values (1548, 0, 0, 1541, 8, NULL, NULL, 6);

-- Generated Fri Apr 26 2019 14:36:55 GMT-0400 (GMT-04:00)
