SELECT ssg.SITE_ID, ssg.TITLE AS "SECTION", ts.TITLE AS SYLLABUS_TITLE, to_char(DESCRIPTION) AS COURSE_TITLE, ts.COURSE_TITLE, count(*)
FROM SAKAI_SITE_GROUP ssg, SAKAI_REALM sr, SAKAI_REALM_RL_GR srrg, TENJIN_SYLLABUS ts, TENJIN_SYLLABUSSECTION ts2 	
WHERE realm_id = '/site/'||ssg.SITE_ID || '/group/' || ssg.GROUP_ID
AND srrg.REALM_KEY = sr.REALM_KEY 
AND srrg.ROLE_KEY = 46
AND srrg.ACTIVE = 1
AND srrg.PROVIDED = 1
AND DESCRIPTION IS NOT NULL 
AND ssg.SITE_ID LIKE '%H2020%'
AND ssg.GROUP_ID = ts2."SECTION" (+)
AND ts.SYLLABUS_ID = ts2.SYLLABUS_ID
AND ts.DELETED = 0
GROUP BY ssg.SITE_ID, ssg.TITLE,  
ts.TITLE, 
ts.COURSE_TITLE ,
to_char(DESCRIPTION) 
ORDER BY ssg.SITE_ID, ssg.TITLE;